
name: Build Colorindo Sonhos APK

on:
  push:
    branches:
      - main
  workflow_dispatch:
  
  - name: Ensure OpenCV AAR
  run: ls app/libs/opencv-4.7.0.aar || echo "Coloque o opencv-4.7.0.aar em app/libs/"


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 34
          build-tools: 34.0.0
          ndk: 25.2.9519653

      - name: Grant execute permission for Gradlew
        run: chmod +x ./gradlew

      - name: Build APK
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: colorindo-sonhos-apk
          path: app/build/outputs/apk/debug/app-debug.apk
